[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/odoo_mates/om_account_accountant,/mnt/extra-addons/field-service,/mnt/extra-addons/web,/mnt/extra-addons/website,/mnt/extra-addons/hr,/mnt/extra-addons/geospatial,/mnt/extra-addons/bank-payment,/mnt/extra-addons/knowledge,/mnt/extra-addons/management-system,/mnt/extra-addons/mis-builder,/mnt/extra-addons/connector-telephony,/mnt/extra-addons/automation,/mnt/extra-addons/payroll,/mnt/extra-addons/sign
data_dir = /var/lib/odoo
admin_passwd = admin_password_change_me

# Multiprocessing (Workers)
workers = 3
max_cron_threads = 1

# Longpolling
proxy_mode = True
xmlrpc_port = 8069
longpolling_port = 8072